CREATE TABLE USERS (
    id LONG NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role ENUM('USER', 'ADMIN') NOT NULL,
    is_enabled BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ANSWERS (
    id LONG NOT NULL AUTO_INCREMENT,
    content VARCHAR(255) NOT NULL,
    correctness BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE QUESTIONS (
    id LONG NOT NULL AUTO_INCREMENT,
    content VARCHAR(255) NOT NULL,
    dtype VARCHAR(255) NOT NULL,
    user_answer VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE EXAMS (
    id LONG NOT NULL AUTO_INCREMENT,
    difficulty_level ENUM('EASY', 'VERY_EASY', 'MEDIUM', 'HARD', 'VERY_HARD') NOT NULL,
    exam_name VARCHAR(255) NOT NULL,
    exam_time INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE EXAM_ATTEMPTS (
    id LONG NOT NULL AUTO_INCREMENT,
    user_id LONG REFERENCES USERS(id),
    exam_name VARCHAR(255) NOT NULL,
    exam_time LONG NOT NULL,
    exam_user_time LONG NOT NULL,
    exam_user_points LONG NOT NULL,
    exam_max_points LONG NOT NULL,
    start_time_date DATETIME NOT NULL,
    end_time_date DATETIME NOT NULL,
    exam_difficulty_level ENUM('EASY', 'VERY_EASY', 'MEDIUM', 'HARD', 'VERY_HARD') NOT NULL,
    PRIMARY KEY (id)
);
-- 1000-01-01 00:00:00
-- 9999-12-31 23:59:59

CREATE TABLE USERS_EXAM_ATTEMPTS (
    user_id LONG REFERENCES USERS(id),
    exam_attempts_id LONG REFERENCES EXAM_ATTEMPTS(id)
);

CREATE TABLE QUESTIONS_ANSWERS (
    question_id LONG REFERENCES QUESTIONS(id),
    answers_id LONG REFERENCES ANSWERS(id)
);

CREATE TABLE EXAMS_QUESTIONS (
    exam_id LONG REFERENCES EXAMS(id),
    questions_id LONG REFERENCES QUESTIONS(id)
);

CREATE TABLE TOKENS (
    id LONG NOT NULL AUTO_INCREMENT,
    user_id LONG REFERENCES USERS(id),
    value VARCHAR(255)
);


